// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eisiypobzxmovtpmkqpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpc2l5cG9ienhtb3Z0cG1rcXB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwMDI4NjUsImV4cCI6MjA1NTU3ODg2NX0.4DpYmHaWaOyQU8cncRD0jex8hYGqnRY5Irk1meg8EAI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);